version: '3.8'
services:

    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: ${MySQL_DB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MySQL_DB_NAME}
          MYSQL_USER: ${MySQL_DB_USER}
          MYSQL_PASSWORD: ${MySQL_DB_PASSWORD}
        ports:
          - '4306:3306'
        volumes:
          - ./mysql:/var/lib/mysql
        networks:
            - symfony
    php:
        container_name: php
        build:
          context: ./php
          args:
              GITHUB_EMAIL: ${GITHUB_EMAIL}
              GITHUB_NAME: ${GITHUB_NAME}
        ports:
          - '9000:9000'
        volumes:
          - ./../apps:/var/www/symfony_docker
        depends_on:
          - database
        networks:
            - symfony
    # nginx:
    #     container_name: nginx
    #     image: nginx:stable-alpine
    #     ports:
    #       - '80:80'
    #     volumes:
    #       - ./apps:/var/www/symfony_docker
    #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #       - php
    #       # - database
networks:
    symfony: